### ISSUE TITLE
Intermittent CI Failure

### ISSUE THREAD

**Issue by little9** [curationexperts/cypripedium#303]
```
Failures:
  1) Contentdm::Importer#work_model with no value uses the default work model
     Failure/Error: return collection if collection.save! != false
     Ldp::Conflict:
       Can't call create on an existing resource
     # ./app/lib/contentdm/collection_builder.rb:27:in `find_or_create'
     # ./app/lib/contentdm/importer.rb:94:in `collection'
     # ./app/lib/contentdm/importer.rb:23:in `initialize'
     # ./spec/lib/contentdm/importer_spec.rb:5:in `new'
     # ./spec/lib/contentdm/importer_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/lib/contentdm/importer_spec.rb:119:in `block (3 levels) in <top (required)>'
     # ./spec/lib/contentdm/importer_spec.rb:138:in `block (4 levels) in <top (required)>'
  2) RdfXmlService#xml returns a valid rdf+xml version of the metadata for a publication
     Failure/Error: File.open(file_fixture('sir_mordred.jpg')) { |file| create(:file_set, content: file) }
     Ldp::Conflict:
       Can't call create on an existing resource
     # ./spec/lib/rdf_xml_service_spec.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/lib/rdf_xml_service_spec.rb:12:in `open'
     # ./spec/lib/rdf_xml_service_spec.rb:12:in `block (2 levels) in <top (required)>'
     # ./spec/lib/rdf_xml_service_spec.rb:16:in `block (2 levels) in <top (required)>'
     # ./spec/lib/rdf_xml_service_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/lib/rdf_xml_service_spec.rb:21:in `block (3 levels) in <top (required)>'
```
